### ISSUE TITLE
Record from Camera

### ISSUE THREAD

**Issue by brunosiqueira** [WritingMinds/ffmpeg-android-java#15]
Is it possible to use the library to record directly from the android camera?
 something like:

>         ffmpeg.execute(" -y -f video4linux2 -s 320x240  -r 25 -i /dev/video0 /testing.mp4", new ExecuteBinaryResponseHandler() {
>
>                @Override
>                public void onStart() {
>                    Log.d("FFMEPG","start");
>                }
>
>                @Override
>                public void onProgress(String message) {
>                    Log.d("FFMEPG",message);
>                }
>
>                @Override
>                public void onFailure(String message) {
>                    Log.e("FFMEPG",message);
>                }
>
>                @Override
>                public void onSuccess(String message) {
>                    Log.d("FFMEPG",message);
>                }
>
>                @Override
>                public void onFinish() {
>                    Log.d("FFMEPG","finish");
>                }
>            });
>        } catch (FFmpegCommandAlreadyRunningException e) {
>            // Handle if FFmpeg is already running
>            Log.e("FFMEPG","error", e);
>        }

**Comment by iamluodong** [comment]
no possible. it is android.
