### ISSUE TITLE
-filter_complex Double quotes issue.

### ISSUE THREAD

**Issue by elsemieni** [WritingMinds/ffmpeg-android-java#20]
Tried with:

-i /sdcard/okobot/entrada.mp4 -i /sdcard/okobot/back_res.png -strict experimental -filter_complex "overlay=0:0" -y /sdcard/okobot/salida.mp4

(Using escape \" to do quotes in string).

Gives error: [AVFilterGraph @ 0xb9567270] No such filter: '"overlay'
(Take attention to the quotes here).

FFMPEG can't use single quotes to work. There's workaround also without use quotes, but doesn't work for multiple -filter_complex combinations (forces the use of double quotes).

**Comment by ab-helly** [comment]
any fix on this?

**Comment by SilkSama** [comment]
The same issue for me too.
Need a fix thx

**Comment by Dakor91** [comment]
You can use -filter_complex without double quotes if you remove all spaces from your filter_complex argument. Just -filter_complex command1;command2;command3

**Comment by ab-helly** [comment]
@Dakor91 thanks, for me turned out the issue was in ffmpeg version and not quotes

**Comment by SilkSama** [comment]
It is ok for me too
thx

**Comment by Dakor91** [comment]
By the way, this issue seems to be equivalent with this one: https://github.com/hiteshsondhi88/ffmpeg-android-java/issues/7
And technically it seems to be fixed, the fixed build is just not in the maven repository, yet

**Comment by SebSob** [comment]
@Dakor91 @elsemieni 
I have the same issue. 
Has this fixed yet? I can not compile to the new 0.2.6 version where the fix was done.. Please help
