### ISSUE TITLE
What about arm v8?

### ISSUE THREAD

**Issue by Tooto** [WritingMinds/ffmpeg-android-java#42]

**Comment by Tooto** [comment]
quick hack to run this library on arm-v8. Tested on sgs6 and 64bit mediatek
This is possible because armv8 include arm-v7 commands

class CpuArchHelper {

    static CpuArch getCpuArch() {
        // check if device is x86

        if (Build.CPU_ABI.equals(getx86CpuAbi())) {
            return CpuArch.x86;
        } else {
            // check if device is armeabi
            if (Build.CPU_ABI.equals(getArmeabiv7CpuAbi())) {
                ArmArchHelper cpuNativeArchHelper = new ArmArchHelper();
                String archInfo = cpuNativeArchHelper.cpuArchFromJNI();
                // check if device is arm v7
                if (cpuNativeArchHelper.isARM_v7_CPU(archInfo)) {
                    // check if device is neon
                    if (cpuNativeArchHelper.isNeonSupported(archInfo)) {
                        return CpuArch.ARMv7_NEON;
                    }
                    return CpuArch.ARMv7;
                }
            }
        }

        //usupported architecture. Ckeck for armv7 support
        if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            // only for gingerbread and newer versions
            String[] architectures = Build.SUPPORTED_ABIS;
            if (architectures != null) {
                for (int i = 0; i < architectures.length; ++i) {
                    if (architectures[i].equals("armeabi-v7a"))
                        return CpuArch.ARMv7;
                }
            }
        }

        return CpuArch.NONE;
    }

    static String getx86CpuAbi() {
        return "x86";
    }

    static String getArmeabiv7CpuAbi() {
        return "armeabi-v7a";
    }
}

**Comment by dominicthomas** [comment]
@Tooto How has finding out what the supported architecture here, helped you run ffmpeg on an armv8 device?

**Comment by dominicthomas** [comment]
@Tooto ah, I see, so this will allow the code to run on an armv8 as an armv8 will include armeabi-v7a as a supported architecture. You could add this as a pull request?

**Comment by Tooto** [comment]
@dominicthomas i think this is hack and very ugly solution. I hope author of this library will add correct support of v8 with compiled ffmpeg.

**Comment by dominicthomas** [comment]
@Tooto indeed that would be much better

**Comment by mlostekk** [comment]
would be great!

**Comment by Shahar2k5** [comment]
I did a pull request for that a while ago… 
https://github.com/WritingMinds/ffmpeg-android-java/pull/57

**Comment by mlostekk** [comment]
wonderfull! thank you very much

**Comment by mlostekk** [comment]
oh, well, just realized you dont have any ffmpegs for 64bit devices compiled

**Comment by Shahar2k5** [comment]
I used that one, you dont need anything else, the ffmpeg files here support armv8, just need to handle it right.

Give it a shot and let me know

**Comment by hiteshsondhi88** [comment]
Thanks for the input guys. armv8 and x86_64 is now officially supported.

**Comment by yuzhidi** [comment]
which commit support armv8 and x86_64 ? thanks a lot!!!

**Comment by anonym24** [comment]
So this solution will allow to use other 64 libraries (other projects, not ffmpeg)?


so it doesn't exclude 64 libraries for all other projects like this solution
```
 ndk {
           "armeabi", "armeabi-v7a", "x86"
 }
```

but just use 32-bit only for ffmpeg, when other libraries still can use native 64 libs?

**Comment by yadavkohi** [comment]
I also have requirement of 64 bit, can anyone tell which commit support that.
