### ISSUE TITLE
APK size is larger than 25MB

### ISSUE THREAD

**Issue by newstarbka** [WritingMinds/ffmpeg-android-java#45]
I'm using ffmpeg library and apk size is too big. Anyone know how to reduce apk size ?

**Comment by ChandanWadhwa** [comment]
Hi 

Your FFmpeg library for android is working fine but the issue is with apk size . Apk size is too large. Could you suggest any idea how to reduce apk size.
Thanks

**Comment by gouravd** [comment]
The increased size is because of 15mb of ARMv7a ffmpeg file, 15mb of ARMv7a-Neon file and 17 mb of X86 ffmpeg file.

So the ideal way is to create different APKs for different architectures.

**Comment by dlet24** [comment]
Hi,

I'm using the library and I noticed that there's a 3 architectures created inside the assets folder (armeabi-v7a, armeabi-v7a-neon, x86) which is causing the APK become too large. How can I prevent it from creating the other folders and retain only 1 architecture folder? 

Best regards!

**Comment by chodison** [comment]
Can you also tell me what did you do compile the ffmpeg library to .so files using android-NDK

**Comment by Vijayadhas** [comment]
I am also facing the APK size issue. Please let me know any idea to reduce the apk size.

**Comment by Vijayadhas** [comment]
I just want to compress the video. I am using 

-y -i /sdcard/videokit/in.mp4 -strict experimental -vcodec libx264 -preset ultrafast -crf 24 -acodec aac -ar 44100 -ac 2 -b 36000k -s 1280x720 -aspect 16:9 -metadata:s:v:0 rotate=0 /sdcard/videokit/out3.mp4

command to compress the video. For this only I am using ffmpeg library. Now my apk size is 30 mb. Is it possible to reduce the apk size?

**Comment by hiteshsondhi88** [comment]
APK Size is now decreased by 7MB and is 18MB now.

**Comment by Tejas-narola** [comment]
Would you please share , How did you decrease APK Size to 7MB? I really need solution.

**Comment by Vijayadhas** [comment]
Refer this. I followed this only to reduce the apk size. https://github.com/WritingMinds/ffmpeg-android-java/issues/66
