### ISSUE TITLE
Unknown encoder 'libfdk_aac'

### ISSUE THREAD

**Issue by itflash** [WritingMinds/ffmpeg-android-java#46]
String cmd = "-i "+mp3Path+" -i "+mp4Path+" -filter_complex [0:a][1:a]amerge,pan=stereo:c0<c0+c2:c1<c1+c3[out] -map 1:v -map [out] -c:v copy -c:a libfdk_aac -shortest "+mergeFilePath;

ffmpeg.execute(cmd, new ExecuteBinaryResponseHandler() {...}

I 'm a newbie to ffmpeg and trying to add background audio to video using the command "cmd" above, but i got Unknown encoder 'libfdk_aac',so what encoder can i use for this? 

Any help would be very appreciate.

**Comment by hiteshsondhi88** [comment]
Hi @itflash 

This library doesn't include libfdk_aac. In order to have it you need to compile FFmpeg on your own.
