### ISSUE TITLE
Update ffmpeg binary to actual version

### ISSUE THREAD

**Issue by kfeoktistoff** [WritingMinds/ffmpeg-android-java#50]
Currently ffmpeg version is 2.4.x is used but [2.8](https://www.ffmpeg.org/download.html#release_2.8) has been already released. Is it planning to update the binary?

**Comment by endryha** [comment]
I am interested in this as well, I heard that there some problems updating to 2.8 but is it possible to update to 2.6?

**Comment by 6uru** [comment]
We plan to update it to the latest version which is 3.0 at the time of this post.
For further discussion, please follow the issue #68
