### ISSUE TITLE
Broken links for javadocs and usages

### ISSUE THREAD

**Issue by mateusgrb** [WritingMinds/ffmpeg-android-java#58]
I believe that in the README you should replace
hiteshsondhi88.github.io/ffmpeg-android-java
with
http://writingminds.github.io/ffmpeg-android-java/

In this last link, the javadocs link is broken too. I think it should be:
http://writingminds.github.io/ffmpeg-android-java/docs

**Comment by hiteshsondhi88** [comment]
@mateusgrb Thanks I have updated the links.
