### ISSUE TITLE
Overlay image on video

### ISSUE THREAD

**Issue by andriantolie** [WritingMinds/ffmpeg-android-java#60]
I tried to overlay image on top of the video with the following command:
`String cmd = "-i /storage/sdcard/DCIM/Camera/VID_20160127_000100.mp4 -i /storage/sdcard/DCIM/Camera/IMG_20160127_000827.jpg -filter_complex overlay=10:10 " + /storage/sdcard/DCIM/Camera/output.mp4";`

but I keep getting 
`W/AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client`. Does somebody have any idea about it?

**Comment by silentsudo** [comment]
@andriantolie how did u solve this issue?

**Comment by sanketsangani** [comment]
@andriantolie we gor same error 
plz post your answer to resolve this issue
thanks in advance.

**Comment by mansigoel94** [comment]
complexCommand = new String[]{ "-i", videoPath, "-i", imagePath,
                "-filter_complex", "overlay=150:50:enable='between(t,0.0,7.0)'",
                "-preset", "ultrafast", "-vcodec", "libx264", "-r", "30", "-profile:v", "baseline", "-threads", "14",
                "-codec:a","copy", outputPath};

where
overlay=x cordinate:y coordinate :enable='between(t,startTime in sec,endTime+1 sec)'
