### ISSUE TITLE
Possible way of metadata change notification?

### ISSUE THREAD

**Issue by Pawly** [WritingMinds/ffmpeg-android-java#62]
Hi,

is it possible to fetch metadata information of radio streams (e.g. icy metadata of artist and title) and register a listener for metadata changes? Otherwise one is forced to poll every couple of seconds and compare old metadata with new one.

**Comment by 6uru** [comment]
I'm afraid this cannot be implemented at this moment.
Maybe we shall consider it in the future, should there be a need.
