### ISSUE TITLE
How to reduce apk size?

### ISSUE THREAD

**Issue by fusionraja** [WritingMinds/ffmpeg-android-java#63]
I using my project for your library. In previous, apk size 8mb. After using your library, apk size 40mb. What i do ? can you provide solution ASAP.
Note: Thanks first of all,. your library is awesome.

**Comment by magicomiralles** [comment]
@fusionraja you need to recompile the binaries including only the libraries that you are going to use. [This guide](http://www.roman10.net/how-to-build-ffmpeg-for-android/) should help you.

**Comment by 6uru** [comment]
Lets discuss all the APK size and related issues in #66

**Comment by thuydx55** [comment]
@fusionraja First, you can remove `neon` support for `armv7` abi (You still need to modify some code). If your app doesn't support `x86` abi, you can also remove it. This will help you reduce your apk size at least 20MB

**Comment by fusionraja** [comment]
Thanks, I reduced apk size from 40 to 20 MB.

**Comment by jaydeepbhanderi007** [comment]
i removed x86 and armv7 from assests. now it's forcestoping app. please help me.

**Comment by thuydx55** [comment]
@jaydeepbhanderi007 Which device are you use for testing? What remaining in the `libs` folder?

**Comment by Mouadabdelghafouraitali** [comment]
@thuydx55 please how  can i know which  CPU architectures my app supprted.

**Comment by thuydx55** [comment]
@Mouadabdelghafouraitali `x86` is nearly dead, you should only care about `armv7` 😄

**Comment by kartikj07** [comment]
How do I remove the x86 architecture from assets? I am unable to find the file related to x86 architecture. Any help will be appreciated. Thanks in advance.

**Comment by thuydx55** [comment]
@kartikj07 use this [one](https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.NdkOptions.html)

**Comment by bipinbharti1357** [comment]
android {
    ...
    aaptOptions {
        ignoreAssetsPattern "!x86"
    }
}

make this line it will help you

**Refer link** [https://github.com/bravobit/FFmpeg-Android/wiki/Reduce-APK-File-Size](url)
