### ISSUE TITLE
Want to Reduce the APK size.

### ISSUE THREAD

**Issue by Vijayadhas** [WritingMinds/ffmpeg-android-java#64]
I just want to compress the video. I am using

`-y -i /sdcard/videokit/in.mp4 -strict experimental -vcodec libx264 -preset ultrafast -crf 24 -acodec aac -ar 44100 -ac 2 -b 36000k -s 1280x720 -aspect 16:9 -metadata:s:v:0 rotate=0 /sdcard/videokit/out3.mp4`

command to compress the video. For this only I am using ffmpeg library. Now my apk size is 30 mb. Is it possible to reduce the apk size?

And also I want to speed up the compression time. it take min one min to compress 40mb video. Is there any way to speed up??

Thanks in advance.

**Comment by neurospeech** [comment]
Delete x86 and armv7-neon libraries and relevant code. I did same and brought down apk size to 10mb.

**Comment by Vijayadhas** [comment]
Hi,

Thank you for the reply :-).. After delete this libraries, app will work on
all the mobiles and tablets?



Thanks and Regards
C. Vijayadhas

On Thu, Feb 11, 2016 at 9:19 AM, NeuroSpeech <notifications@github.com>
wrote:

> Delete x86 and armv7-neon libraries and relevant code. I did same and
> brought down apk size to 10mb.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WritingMinds/ffmpeg-android-java/issues/64#issuecomment-182691797>
> .
>



-- 
"Do not wait for leaders;
do it alone, person to person"

**Comment by neurospeech** [comment]
Yes, as long as they do not have x86 processor. For x86 processor you will need relevant files. In that case you can split app into two different apps.

**Comment by Vijayadhas** [comment]
Oh. Gr8.. Thanks for the suggestion.. :-)


Thanks and Regards
C. Vijayadhas

On Thu, Feb 11, 2016 at 10:50 AM, NeuroSpeech <notifications@github.com>
wrote:

> Yes, as long as they do not have x86 processor. For x86 processor you will
> need relevant files. In that case you can split app into two different apps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WritingMinds/ffmpeg-android-java/issues/64#issuecomment-182716812>
> .
>



-- 
"Do not wait for leaders;
do it alone, person to person"

**Comment by hiteshsondhi88** [comment]
Lets discuss all the APK size and related issues in #66

**Comment by gulzar1996** [comment]
This is kind of a hack but the initial apk size can be reduced by downloading the .so files after installation.

**Comment by Aditya94A** [comment]
@gulzar1996 I remember reading a google blog post recently where they explicitly forbade doing this, as it's really just pushing executable code directly to the client outside of the play store review process and is likely to get you banned.
