### ISSUE TITLE
ffmpeg Encoder (codec mp3) not found for output stream #0:0

### ISSUE THREAD

**Issue by coolrukshan** [WritingMinds/ffmpeg-android-java#65]
When I try to convert a mp4 file to a mp3 file, it fails: 
Error message 
Encoder (codec mp3) not found for output stream #0:0

**Comment by hiteshsondhi88** [comment]
libmp3lame is now included in the latest version.

**Comment by liuyu520** [comment]
yum --enablerepo=rpmfusion-free-updates install lame-devel
上面命令如果报错,则执行:
yum install lame-devel
