### ISSUE TITLE
Command wont work anymore after changing it to string[].

### ISSUE THREAD

**Issue by magicomiralles** [WritingMinds/ffmpeg-android-java#67]
This is the error that I am getting:

`Unrecognized option 'y -i /data/data/com.Gifaroo.Gifaroo/files/my_file.gif -vf scale=700:-1 -preset superfast /data/data/com.Gifaroo.Gifaroo/files/output_mp4.mp4'.`

This same command was working fine when Fffmeg.execute() would take a string type instead of a string[] array. I already tried surrounding the file names with '', but it still wont work.

The string itself before being converted, looks as follows:

`"-y -i /data/data/com.Gifaroo.Gifaroo/files/my_file.gif -vf scale=700:-1 -preset superfast /data/data/com.Gifaroo.Gifaroo/files/output_mp4.`

- If you look at the error, for some reason the "-" symbol at the beginning is gone. I did try to add an      empty space before the -y. However, I get the following error:

`-y -i /data/data/com.Gifaroo.Gifaroo/files/my_file.gif -vf scale=700:-1 -preset superfast /data/data/com.Gifaroo.Gifaroo/files/output_mp4.mp4: No such file or directory`

I checked and the file is there but for some reason ffmpeg cannot access it anymore.

**Comment by magicomiralles** [comment]
All I had to do was use String.split(); on the command string and pass the result to ffmpeg.execute();

**Comment by hyd00** [comment]
@magicomiralles I'm having same issue sir, 
my command is:
`String cmd =  "-i /storage/emulated/0/jd.m4a -i /storage/emulated/0/jd.m4a -filter_complex [0:a]volume=0.99[a1];[1:a]volume=0.3[a2];[a1][a2]amerge=inputs=2,volume=1.3,pan=stereo|c0<c0+c2|c1<c1+c3[aout] -map [aout] -strict -2 /storage/emulated/0/mergefile.m4a"` 

And then I do
`String[] command = cmd.split(" ");`

And then pass `command` in `ffmpeg.execute()`

But error is coming `Unrecognised option 'filter_complex [0:a]volume=0.99[a1];[1:a]volume=0.3[a2];[a1][a2]amerge=inputs=2,volume=1.3,pan=stereo|c0<c0+c2|c1<c1+c3[aout]'`

Please help any suggestion? Im stuck.
