### ISSUE TITLE
New release for FFmpeg 3.0

### ISSUE THREAD

**Issue by HuyTranQ** [WritingMinds/ffmpeg-android-java#68]
Can you update your project to FFmpeg version 3.0 please?

**Comment by thuydx55** [comment]
It's done by my PR #70

**Comment by gouravd** [comment]
@thuydx55 Could you help me with the steps for building ffmpeg (3.0). The outputs are too big (>17mb) for our use and we only need very few features. So I assume if I build it by removing most of the stuff not required by me, I can reduce the size.

**Comment by hiteshsondhi88** [comment]
I have released a new version 0.3.2 which uses FFmpeg 0.3.1.
