### ISSUE TITLE
Space in path

### ISSUE THREAD

**Issue by protoss5482** [WritingMinds/ffmpeg-android-java#7]
1. /storage/emulated/0/Music/They Might Be Giants - Seven Days Of The We.mp3
 result:
 /storage/emulated/0/Music/They: No such file or directory

2. "/storage/emulated/0/Music/They Might Be Giants - Seven Days Of The We.mp3"
result:
"/storage/emulated/0/Music/They: No such file or directory

3. '/storage/emulated/0/Music/They Might Be Giants - Seven Days Of The We.mp3'
result:
'/storage/emulated/0/Music/They: No such file or directory

4. /storage/emulated/0/Music/They%20Might%20Be%20Giants%20-%20Seven%20Days%20Of%20The%20We.mp3
result:
/storage/emulated/0/Music/They%20Might%20Be%20Giants%20-%20Seven%20Days%20Of%20The%20We.mp3: No such file or directory

full command:

-i  /storage/emulated/0/Music/They Might Be Giants - Seven Days Of The We.mp3 -strict experimental -ab 48000 -ac 2 -ar 22050  /storage/emulated/0/Music/out.mp4

**Comment by Thiru2Moorthy** [comment]
I followed your suggestions of using single and double quote and also tried using escape sequence  while using path with spaces.

However the log cat still source same error.

Any other suggestions please.

**Comment by Thiru2Moorthy** [comment]
I discovered that calling "Runtime.getRuntime().exec();" with a string array as parameter instead of string solved this issue, by passing the commands as an array allowed me to include  spaces. 

Ex: Process run(String command[]) {
        Process process = null;
        try {
            process = Runtime.getRuntime().exec(command);
        } catch (IOException e) {
            Log.e("Exception while trying to run: " + command, e);
        }
        return process;
    }

**Comment by gderaco** [comment]
This library uses Runtime.getRuntime().exec(String) method wich is not good if you have for example double quotes ( see https://stackoverflow.com/questions/14078799/getruntime-exec-with-double-quotes-in-command ). Need to switch to exec(String[] cmdarray)

**Comment by javiermanzano** [comment]
Any solution with this @gderaco ?

**Comment by javiermanzano** [comment]
I've just done a pull request for this: https://github.com/hiteshsondhi88/ffmpeg-android-java/pull/17

**Comment by dayeba** [comment]
i'm having the same issue, i tried escaping and my final command is
**ffmpeg -y -i /storage/emulated/0/Download/1\ -\ 1.mp4 -f mp4 -vcodec libx264 -maxrate 750k -ss 0.0 -to 120.0 -vf scale=480:-2 -r 24 -strict -2 /storage/emulated/0/DCIM/Camera/aaa.mp4**
and logcat says
**Unrecognized option '\'.
Error splitting the argument list: Option not found**
Do I have to use **Runtime.getRuntime().exec()** then?

**Comment by rafaelekol** [comment]
I have same issue, how I can use your commit #17?

**Comment by Dakor91** [comment]
These changes don't seem to be in the Maven Repository, yet.. any plans for updating the repository?

**Comment by symphonyrecords** [comment]
I've fixed this problem by doing this [stackoverflow](https://stackoverflow.com/a/51594776/6017001)
