### ISSUE TITLE
How can I support armabiv8 (Note 5) ?

### ISSUE THREAD

**Issue by rjaiswal1808** [WritingMinds/ffmpeg-android-java#72]
Current support is only for 
armeabi-v7a
armeabi-v7a-neao
x86

How can I support other CPU architectures?

**Comment by thuydx55** [comment]
Currently, if your processor support `armaebi-v7a` architecture, the demo app still running on your devices. As far as i know, your device (Note 5) still stupport `armaebi-v7a`

**Comment by rjaiswal1808** [comment]
Thanks. Its working on that.
