### ISSUE TITLE
Prevent reloading of FFMPEG library.

### ISSUE THREAD

**Issue by rjaiswal1808** [WritingMinds/ffmpeg-android-java#74]
We load library by calling ffmpeg.loadBinary() method. I'd like to know if there is any way I can check before loading it again if its already loaded or not.

**Comment by hiteshsondhi88** [comment]
Currently there is no way to check or prevent reloading of binary and I don't think it will be required by majority of users.

I am going to close this but can consider if larger group of people needs this.
