### ISSUE TITLE
Request for update dependency

### ISSUE THREAD

**Issue by RaviKoradiya** [WritingMinds/ffmpeg-android-java#77]
Hello Hitesh sir.

   FFMPEG  awesome tool for compressing video thanks for that.
But I am suffering from spacing issue  after that I had check your code and I had show that you solve it in belove URL.

[https://github.com/WritingMinds/ffmpeg-android-java/commit/9f06d89f40d974089982b7c3ac6698b363089241](url)

but my problem is I am curruntly using dependency 

> compile 'com.github.hiteshsondhi88.libffmpeg:FFmpegAndroid:0.2.5'

so can you please update new compile **dependency **its help me lots.
I will be grateful to you.

Thanks,

**Comment by hiteshsondhi88** [comment]
Updated to 0.3.2 and can be used using -

compile 'com.writingminds:FFmpegAndroid:0.3.2'

**Comment by RaviKoradiya** [comment]
Thank you, so much.

**Comment by patelmanthan777** [comment]
Thank you, so much.Very helpful.

**Comment by Hassaan68** [comment]
now execute method will take string array as first argument?
