### ISSUE TITLE
"Warning: linker ... has text relocations" issue

### ISSUE THREAD

**Issue by ruha9005** [WritingMinds/ffmpeg-android-java#80]
Problem: `"WARNING: linker: *******files/ffmpeg has text relocations. This is wasting memory and prevents security hardening. Please fix."`

Possible solution:
Change `process = Runtime.getRuntime().exec(commandString);` in `...\libffmpeg\ShellCommand.java` in accordance with the proposed solution:
[http://stackoverflow.com/a/14078844/2806800](url)

**Comment by soster** [comment]
I can confirm this problem.
