### ISSUE TITLE
m3u8 source does not work

### ISSUE THREAD

**Issue by vladsd** [WritingMinds/ffmpeg-android-java#81]
Trying to run simple command:
-loglevel 99 -i "http://nasatv-lh.akamaihd.net/i/NASA_101@319270/master.m3u8" -c:v copy -c:a copy -threads 0 -hls_time 10 -hls_list_size 6 -hls_wrap 60 -start_number 1 -y "/sdcard/stream.m3u8""

It says input file not found: "http://nasatv-lh.akamaihd.net/i/NASA_101@319270/master.m3u8"

Same command works fine in command line. Any ideas what is the problem?

Thank you all.

**Comment by vladsd** [comment]
just add this to manifest <uses-permission android:name="android.permission.INTERNET"></uses-permission>

**Comment by devslava** [comment]
`<uses-permission android:name="android.permission.INTERNET" />`
