### ISSUE TITLE
Not working on nexus 5x

### ISSUE THREAD

**Issue by shubhamvishnoi-kiwi** [WritingMinds/ffmpeg-android-java#82]
Hi,
this library works for samsung devices but when using with nexus 5x it gives error like device not supported.

please help.

**Comment by hiteshsondhi88** [comment]
Try the latest version.

**Comment by shubhamvishnoi-kiwi** [comment]
Hi,

i have tried latest version and now it is working on nexus device. 
Thanks for your great efforts.
