### ISSUE TITLE
What is the difference between onSuccess and onFinish?

### ISSUE THREAD

**Issue by hendraanggrian** [WritingMinds/ffmpeg-android-java#84]
Both `LoadBinaryResponseHandler` and `ExecuteBinaryResponseHandler` have `onSuccess()` and `onFinish()` with very little explanation on which cases will they execute. [javadoc link](http://hiteshsondhi88.github.io/ffmpeg-android-java/docs/) found in this [site](http://writingminds.github.io/ffmpeg-android-java/) are also down. Can someone explain to me the difference between those two?

**Comment by gouravd** [comment]
You can think Onfinish as final (of the Try-Catch-Final paradigm). onFinish is called irrespective of whether the process succeeded or errored out. If succeeded onSuccess is called prior to onFinish

**Comment by hendraanggrian** [comment]
@gouravd okay thanks for clearing up things for me. Someone can close this now.
